version: "3"

services:
  web:
    container_name: takenotes
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: db url here