name: Build Deploy

# Trigger deployment only on push to master branch
on:
    push:
        branches: [main]

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Deploy in EC2
        uses: appleboy/ssh-action@master

        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          host: ${{secrets.HOST_IP}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_KEY}}
          envs: DATABASE_URL
          script: |
            touch hello.txt

                  