name: Build Deploy

# Trigger deployment only on push to master branch
on:
    push:
        branches: [main]

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key:${{ secrets.SSH_KEY }}
          name: id_rsa
          known_host: ${{ secrets.HOST_DNS }}
      - name: rsync over ssh
        run: |
            ssh ec2-user@ip-172-31-30-138
            touch hello.txt

          # TARGET: ${{ secrets.TARGET_DIR }}

                  